apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=0.0.0.0
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=0.0.0.0
    - --feature-gates=TTLAfterFinished=true,EphemeralContainers=true
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --policy-config-file=/etc/kubernetes/scheduler-policy-config.json
    - --port=10251
    - --profiling=false
    image: registry-internal.adp.aliyuncs.com:5000/oecp/kube-scheduler:v1.20.4-aliyun.1
    imagePullPolicy: IfNotPresent
#    livenessProbe:
#      failureThreshold: 8
#      httpGet:
#        path: /healthz
#        port: 10259
#        scheme: HTTPS
#      initialDelaySeconds: 10
#      periodSeconds: 10
#      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
#    startupProbe:
#      failureThreshold: 24
#      httpGet:
#        path: /healthz
#        port: 10259
#        scheme: HTTPS
#      initialDelaySeconds: 10
#      periodSeconds: 10
#      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler-policy-config.json
      name: scheduler-policy-config
      readOnly: true
  hostNetwork: true
  nodeName: master-1
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/localtime
      type: File
    name: localtime
  - hostPath:
      path: /etc/kubernetes/scheduler-policy-config.json
      type: File
    name: scheduler-policy-config
status: {}